### ISSUE TITLE
additional flag needed (--manual-public-ip-logging-ok)

### ISSUE THREAD

**Issue by jschmied** [steinsag/hosteurope-letsencrypt#22]
I had to put

# certbot Kommando zusammenbauen
cmd = 'certbot certonly -n --manual --agree-tos --expand --manual-public-ip-logging-ok'

in to keep it working

**Comment by steinsag** [comment]
What certbot version are you using. There [were reports](https://community.letsencrypt.org/t/certbot-renew-failing-due-to-missing-manual-public-ip-logging-ok/164248/2) in the past that this parameter is required due to a bug in an older version.

I just renewed my certs a few days ago and everything went fine without the flag. I got certbot version 1.21.0 on Ubuntu.

My version of certbot doesn't know about this flag.
